services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: atlas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d atlas"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4-management
    container_name: atlas-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_JWT_EXPIRATION: ${REFRESH_JWT_EXPIRATION}
      ACCESS_JWT_EXPIRATION: ${ACCESS_JWT_EXPIRATION}
      RESEND_API_KEY: ${RESEND_API_KEY}
      MAX_ATTEMPTS: ${MAX_ATTEMPTS}
      INITIAL_INTERVAL: ${INITIAL_INTERVAL}


volumes:
  postgres_data: